# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Debug build is created for this lane"
  lane :debug do
    # add actions here: https://docs.fastlane.tools/actions
      puts("this is Debug 🚀 lane")
     # build_app(scheme: "JenkinsTest")
   	 #  build_app(export_method: "development", export_options: { provisioningProfiles: { "com.tick.ios" => "TickDevProvisioning" }})

gym(scheme: "JenkinsTest", clean: true, silent: true, include_bitcode: false, export_options:{
			compileBitcode: false,
			method: "development",
			signingStyle: "manual",
  			provisioningProfiles:{
    				"com.tick.ios": "TickDevProvisioning"
  			}
		})
end

lane :release do
    # add actions here: https://docs.fastlane.tools/actions
      puts("this is Release 🚀 lane")
     # build_app(scheme: "JenkinsTest")
   	 #  build_app(export_method: "development", export_options: { provisioningProfiles: { "com.tick.ios" => "TickDevProvisioning" }})

gym(scheme: "JenkinsTest", clean: true, silent: true, include_bitcode: false, export_options:{
			compileBitcode: false,
			method: "app-store",
			signingStyle: "manual",
  			provisioningProfiles:{
    				"com.tick.ios": "TickAppstore"
  			}
		})
end

desc "Creates slack message"
lane :slack_message do
       slack(
           message: "App successfully created build in workspace.",
           success: true,
           slack_url: "https://hooks.slack.com/services/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"
       )
   end


end
